import os

THRESHOLD_LOW_MAX = int(os.getenv("HOTSPOT_THRESHOLD_LOW_MAX", "5"))
THRESHOLD_MEDIUM_MAX = int(os.getenv("HOTSPOT_THRESHOLD_MEDIUM_MAX", "15"))
THRESHOLD_HIGH_MAX = int(os.getenv("HOTSPOT_THRESHOLD_HIGH_MAX", "30"))

HOTSPOT_CACHE_TTL_SECONDS = int(os.getenv("HOTSPOT_CACHE_TTL_SECONDS", "21600"))
CRIME_API_BASE = os.getenv("CRIME_API_BASE", "http://127.0.0.1:8000").rstrip("/")
